#!/bin/sh

#SBATCH --job-name=ONT_NF_master
#SBATCH --partition=GENOA
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=50G
#SBATCH --time=150:00:00
#SBATCH -A lade
#SBATCH --output=log_%j
#SBATCH --error=err_%j

module load singularity/3.10.4
module load java

pipeline=/orfeo/scratch/area/lvaleriani/nf-locate
/orfeo/scratch/area/lvaleriani/nextflow run $pipeline/main.nf \
    -c $pipeline/myconfig \
    --input $pipeline/test/input_organoids.csv \
    --outdir $pipeline/results_organoids \
    -profile singularity \
    -resume
