#!/bin/sh
#### Cluster specific arguments ####

#SBATCH --job-name=ONT_NF_master
#SBATCH --partition=EPYC
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=1
#SBATCH --mem=10G
#SBATCH --time=12:00:00
#SBATCH -A lade
#SBATCH --output=log

module load singularity/3.10.4
module load java

pipeline=/orfeo/LTS/LADE/LT_storage/lvaleriani/LR_Pipeline_DNA
/orfeo/LTS/LADE/LT_storage/lvaleriani/nextflow/nextflow run $pipeline/main.nf \
    -resume \
    -c $pipeline/myconfig \
    --input $pipeline/organoids.csv \
    --outdir $pipeline/res_organoids \
    -profile singularity
